import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'he' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'he';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.setAttribute('dir', language === 'he' ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const translations = language === 'he' ? heTranslations : enTranslations;
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        dir: language === 'he' ? 'rtl' : 'ltr',
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

const heTranslations: Record<string, string> = {
  "nav.dashboard": "דשבורד",
  "nav.deliveries": "משלוחים",
  "nav.entities": "ישויות",
  "nav.data": "נתונים",
  "nav.finance": "כספים",
  "nav.settings": "הגדרות",
  "nav.live": "מנג'ר לייב",
  "nav.map": "מפה חיה",
  "nav.archive": "ארכיון",
  "nav.tracking": "מעקב משלוחים",
  "nav.deliveryTracking": "מעקב משלוחים",
  "nav.history": "משלוחים",
  "nav.couriers": "שליחים",
  "nav.restaurants": "מסעדות",
  "nav.managers": "מנהלים",
  "nav.customers": "לקוחות",
  "nav.deliveryDetails": "פרטי משלוח",
  "nav.courierDetails": "פרטי שליח",
  "nav.restaurantDetails": "פרטי מסעדה",
  "nav.customerDetails": "פרטי לקוח",
  "nav.businessManagement": "ניהול עסק",
  "nav.dataCenter": "מרכז נתונים",
  "nav.reports": "דוחות",
  "nav.adminMode": "מצב מנהל",
  "nav.appearance": "עיצוב ומראה",
  "nav.accountSettings": "הגדרות חשבון",
  "nav.entityManagement": "ניהול ישויות",
  "nav.monthlyPayout": "תשלום חודשי",
  "nav.purchaseHistory": "היסטוריית רכישות",
  "common.search": "חיפוש",
  "common.filter": "סינון",
  "common.export": "ייצוא",
  "common.import": "ייבוא",
  "common.add": "הוסף",
  "common.edit": "ערוך",
  "common.delete": "מחק",
  "common.cancel": "ביטול",
  "common.save": "שמור",
  "common.close": "סגור",
  "common.reset": "איפוס",
  "common.clear": "נקה",
  "common.apply": "החל",
  "common.confirm": "אישור",
  "common.yes": "כן",
  "common.no": "לא",
  "common.all": "הכל",
  "common.none": "ללא",
  "common.loading": "טוען...",
  "common.error": "שגיאה",
  "common.success": "הצלחה",
  "common.warning": "אזהרה",
  "common.info": "מידע",
  "common.more": "עוד",
  "common.actions": "פעולות",
  "common.options": "אפשרויות",
  "common.view": "צפייה",
  "common.back": "חזור",
  "common.next": "הבא",
  "common.previous": "הקודם",
  "common.refresh": "רענן",
  "common.select": "בחר",
  "common.selected": "נבחרו",
  "common.total": "סה\"כ",
  "status.pending": "ממתין",
  "status.assigned": "שובץ",
  "status.pickedUp": "נאסף",
  "status.onTheWay": "בדרך",
  "status.delivered": "נמסר",
  "status.cancelled": "בוטל",
  "status.failed": "נכשל",
  "status.returned": "הוחזר",
  "courierStatus.available": "זמין",
  "courierStatus.busy": "עסוק",
  "courierStatus.offline": "לא פעיל",
  "priority.low": "נמוכה",
  "priority.normal": "רגילה",
  "priority.high": "גבוהה",
  "priority.urgent": "דחוף",
  "filters.status": "סטטוס",
  "filters.date": "תאריכים",
  "filters.branch": "סניף",
  "filters.restaurant": "מסעדה",
  "filters.courier": "שליח",
  "filters.allBranches": "כל הסניפים",
  "filters.allRestaurants": "כל המסעדות",
  "filters.allCouriers": "כל השליחים",
  "filters.searchBranch": "חיפוש סניף...",
  "filters.searchRestaurant": "חיפוש מסעדה...",
  "filters.searchCourier": "חיפוש שליח...",
  "filters.noResults": "לא נמצאו תוצאות",
  "filters.advanced": "מסננים מתקדמים",
  "filters.clear": "נקה מסננים",
  "filters.apply": "החל מסננים",
  "dateRange.all": "כל התאריכים",
  "dateRange.today": "היום",
  "dateRange.week": "שבוע אחרון",
  "dateRange.month": "חודש אחרון",
  "dateRange.custom": "טווח מותאם...",
  "dateRange.from": "מתאריך",
  "dateRange.to": "עד תאריך",
  "table.showingResults": "מציג {count} משלוחים",
  "table.noDeliveries": "לא נמצאו משלוחים",
  "table.selectAll": "בחר הכל",
  "table.deselectAll": "בטל הכל",
  "table.selectedItems": "{count} נבחרו",
  "table.actions": "פעולות",
  "table.viewDetails": "צפה בפרטים",
  "table.editDelivery": "ערוך משלוח",
  "table.deleteDelivery": "מחק משלוח",
  "table.duplicateDelivery": "שכפל משלוח",
  "table.bulkActions": "פעולות על מספר פריטים",
  "table.columns": "עמודות",
  "table.rowHeight": "גובה שורה",
  "delivery.id": "מזהה",
  "delivery.orderNumber": "מספר הזמנה",
  "delivery.status": "סטטוס",
  "delivery.priority": "עדיפות",
  "delivery.type": "סוג משלוח",
  "delivery.customer": "לקוח",
  "delivery.address": "כתובת",
  "delivery.phone": "טלפון",
  "delivery.courier": "שליח",
  "delivery.restaurant": "מסעדה",
  "delivery.branch": "סניף",
  "delivery.amount": "סכום",
  "delivery.payment": "תשלום",
  "delivery.notes": "הערות",
  "delivery.createdAt": "נוצר ב",
  "delivery.updatedAt": "עודכן ב",
  "delivery.estimatedTime": "זמן משוער",
  "delivery.actualTime": "זמן בפועל",
  "delivery.items": "פריטים",
  "delivery.details": "פרטי משלוח",
  "delivery.new": "משלוח חדש",
  "delivery.edit": "עריכת משלוח",
  "editDialog.general": "כללי",
  "editDialog.customer": "לקוח",
  "editDialog.items": "פריטים",
  "editDialog.logistics": "לוגיסטיקה",
  "editDialog.payment": "תשלום",
  "editDialog.tracking": "מעקב",
  "editDialog.communication": "תקשורת",
  "editDialog.metadata": "מטא-דאטה",
  "settings.appearance": "מראה",
  "settings.language": "שפה",
  "settings.theme": "ערכת צבעים",
  "settings.darkMode": "מצב כהה",
  "settings.autoTheme": "מצב אוטומטי",
  "settings.seasonalTheme": "מצב חגיגי",
  "settings.notifications": "התראות",
  "settings.account": "חשבון",
  "settings.profile": "פרופיל",
  "settings.security": "אבטחה",
  "settings.privacy": "פרטיות",
  "settings.about": "אודות",
  "settings.system": "הגדרות מערכת",
  "settings.business": "ניהול עסק",
  "settings.help": "עזרה",
  "language.he": "עברית",
  "language.en": "English",
  "theme.green": "ירוק",
  "theme.blue": "כחול",
  "theme.purple": "סגול",
  "theme.orange": "כתום",
  "theme.pink": "ורוד",
  "theme.red": "אדום",
  "seasonal.none": "רגיל",
  "seasonal.hanukkah": "חנוכה",
  "seasonal.purim": "פורים",
  "seasonal.passover": "פסח",
  "seasonal.independence": "יום העצמאות",
  "seasonal.summer": "קיץ",
  "seasonal.winter": "חורף",
  "dashboard.welcome": "ברוכים הבאים",
  "dashboard.overview": "סקירה כללית",
  "dashboard.statistics": "סטטיסטיקות",
  "dashboard.recentActivity": "פעילות אחרונה",
  "dashboard.quickActions": "פעולות מהירות",
  "dashboard.activeDeliveries": "משלוחים פעילים",
  "dashboard.availableCouriers": "שליחים פנויים",
  "dashboard.activeRestaurants": "מסעדות פעילות",
  "dashboard.todayRevenue": "הכנסות היום",
  "dashboard.avgDeliveryTime": "זמן ממוצע למשלוח",
  "dashboard.completedToday": "הושלמו היום",
  "dashboard.cancelledToday": "בוטלו היום",
  "dashboard.pendingOrders": "ממתינים לשיבוץ",
  "dashboard.assignedOrders": "משלוחים ששובצו",
  "dashboard.pickedUpOrders": "משלוחים שנאספו",
  "dashboard.onTheWayOrders": "משלוחים בדרך",
  "dashboard.deliveredOrders": "משלוחים שנמסרו",
  "topbar.notifications": "התראות",
  "topbar.userMenu": "תפריט משתמש",
  "topbar.profile": "פרופיל",
  "topbar.settings": "הגדרות",
  "topbar.logout": "התנתק",
  "topbar.balance": "יתרה",
  "sidebar.selectBusiness": "בחר בית עסק",
  "sidebar.collapse": "כווץ",
  "sidebar.expand": "הרחב",
  "sidebar.systemControl": "שליטה במערכת",
  "sidebar.acceptDeliveries": "קבלת משלוחים",
  "sidebar.autoAssign": "שיבוץ אוטומטי",
  "sidebar.deliveryBalance": "יתרת משלוחים",
  "sidebar.businessManagement": "ניהול עסק",
  "sidebar.systemSettings": "הגדרות",
  "sidebar.help": "עזרה",
  "sidebar.statistics": "סטטיסטיקה",
  "sidebar.reports": "דוחות",
  "sidebar.finances": "כספים",
  "sidebar.settings": "הגדרות",
  "sidebar.noActiveCouriers": "❌ לא ניתן להפעיל קבלת משלוחים ללא שליחים מחוברים!",
  "breadcrumbs.home": "בית",
  "breadcrumbs.shipments": "משלוחים",
  "breadcrumbs.operatingHours": "שעות פעילות",
  "breadcrumbs.deliveryZones": "אזורי משלוח",
  "breadcrumbs.distancePricing": "תמחור לפי מרחק",
  "breadcrumbs.performance": "ביצועים",
  "breadcrumbs.shipmentBalance": "יתרת משלוחים",
  "search.deliveries": "חיפוש משלוחים...",
  "search.orderNumber": "חיפוש לפי מספר הזמנה...",
  "search.customer": "חיפוש לפי לקוח...",
  "search.restaurant": "חיפוש לפי מסעדה...",
  "search.general": "חיפוש משלוחים... (Ctrl+K)",
  "search.courierDetails": "חיפוש לפי מספר הזמנה, לקוח או מסעדה...",
  "export.title": "ייצוא נתונים",
  "export.format": "פורמט",
  "export.fields": "שדות",
  "export.selectFields": "בחר שדות",
  "export.allFields": "כל השדות",
  "export.download": "הורד",
  "export.csv": "CSV",
  "export.excel": "Excel",
  "export.pdf": "PDF",
  "time.minutes": "דקות",
  "time.hours": "שעות",
  "time.days": "ימים",
  "time.ago": "לפני",
  "time.justNow": "ממש עכשיו",
  "action.view": "צפייה",
  "action.edit": "עריכה",
  "action.delete": "מחיקה",
  "action.duplicate": "שכפול",
  "action.assign": "שיבוץ",
  "action.cancel": "ביטול",
  "action.complete": "השלמה",
  "action.print": "הדפסה",
  "action.share": "שיתוף",
  "notification.success": "הפעולה בוצעה בהצלחה",
  "notification.error": "אירעה שגיאה",
  "notification.saved": "השינויים נשמרו",
  "notification.deleted": "הפריט נמחק",
  "notification.assigned": "המשלוח שובץ",
  "notification.cancelled": "המשלוח בוטל",
  "empty.noDeliveries": "אין משלוחים להצגה",
  "empty.noResults": "לא נמצאו תוצאות",
  "empty.noData": "אין נתונים זמינוים",
  "empty.addFirst": "הוסף את הראשון",
  "validation.required": "שדה חובה",
  "validation.invalidEmail": "כתובת אימייל לא תקינה",
  "validation.invalidPhone": "מספר טלפון לא תקין",
  "error.loadFailed": "טעינת הנתונים נכשלה",
  "error.saveFailed": "שמירת הנתונים נכשלה",
  "error.connectionFailed": "החיבור לשרת נכשל"
};

const enTranslations: Record<string, string> = {
  "nav.dashboard": "Dashboard",
  "nav.deliveries": "Deliveries",
  "nav.entities": "Entities",
  "nav.data": "Data",
  "nav.finance": "Finance",
  "nav.settings": "Settings",
  "nav.live": "Live Manager",
  "nav.map": "Live Map",
  "nav.archive": "Archive",
  "nav.tracking": "Tracking",
  "nav.deliveryTracking": "Delivery Tracking",
  "nav.history": "History",
  "nav.couriers": "Couriers",
  "nav.restaurants": "Restaurants",
  "nav.managers": "Managers",
  "nav.customers": "Customers",
  "nav.deliveryDetails": "Delivery Details",
  "nav.courierDetails": "Courier Details",
  "nav.restaurantDetails": "Restaurant Details",
  "nav.customerDetails": "Customer Details",
  "nav.businessManagement": "Business Management",
  "nav.dataCenter": "Data Center",
  "nav.reports": "Reports",
  "nav.adminMode": "Admin Mode",
  "nav.appearance": "Appearance",
  "nav.accountSettings": "Account Settings",
  "nav.entityManagement": "Entity Management",
  "nav.monthlyPayout": "Monthly Payout",
  "nav.purchaseHistory": "Purchase History",
  "common.search": "Search",
  "common.filter": "Filter",
  "common.export": "Export",
  "common.import": "Import",
  "common.add": "Add",
  "common.edit": "Edit",
  "common.delete": "Delete",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.close": "Close",
  "common.reset": "Reset",
  "common.clear": "Clear",
  "common.apply": "Apply",
  "common.confirm": "Confirm",
  "common.yes": "Yes",
  "common.no": "No",
  "common.all": "All",
  "common.none": "None",
  "common.loading": "Loading...",
  "common.error": "Error",
  "common.success": "Success",
  "common.warning": "Warning",
  "common.info": "Info",
  "common.more": "More",
  "common.actions": "Actions",
  "common.options": "Options",
  "common.view": "View",
  "common.back": "Back",
  "common.next": "Next",
  "common.previous": "Previous",
  "common.refresh": "Refresh",
  "common.select": "Select",
  "common.selected": "selected",
  "common.total": "Total",
  "status.pending": "Pending",
  "status.assigned": "Assigned",
  "status.pickedUp": "Picked Up",
  "status.onTheWay": "On The Way",
  "status.delivered": "Delivered",
  "status.cancelled": "Cancelled",
  "status.failed": "Failed",
  "status.returned": "Returned",
  "courierStatus.available": "Available",
  "courierStatus.busy": "Busy",
  "courierStatus.offline": "Offline",
  "priority.low": "Low",
  "priority.normal": "Normal",
  "priority.high": "High",
  "priority.urgent": "Urgent",
  "filters.status": "Status",
  "filters.date": "Dates",
  "filters.branch": "Branch",
  "filters.restaurant": "Restaurant",
  "filters.courier": "Courier",
  "filters.allBranches": "All Branches",
  "filters.allRestaurants": "All Restaurants",
  "filters.allCouriers": "All Couriers",
  "filters.searchBranch": "Search branch...",
  "filters.searchRestaurant": "Search restaurant...",
  "filters.searchCourier": "Search courier...",
  "filters.noResults": "No results found",
  "filters.advanced": "Advanced Filters",
  "filters.clear": "Clear Filters",
  "filters.apply": "Apply Filters",
  "dateRange.all": "All Dates",
  "dateRange.today": "Today",
  "dateRange.week": "Last Week",
  "dateRange.month": "Last Month",
  "dateRange.custom": "Custom Range...",
  "dateRange.from": "From Date",
  "dateRange.to": "To Date",
  "table.showingResults": "Showing {count} deliveries",
  "table.noDeliveries": "No deliveries found",
  "table.selectAll": "Select All",
  "table.deselectAll": "Deselect All",
  "table.selectedItems": "{count} selected",
  "table.actions": "Actions",
  "table.viewDetails": "View Details",
  "table.editDelivery": "Edit Delivery",
  "table.deleteDelivery": "Delete Delivery",
  "table.duplicateDelivery": "Duplicate Delivery",
  "table.bulkActions": "Bulk Actions",
  "table.columns": "Columns",
  "table.rowHeight": "Row Height",
  "delivery.id": "ID",
  "delivery.orderNumber": "Order Number",
  "delivery.status": "Status",
  "delivery.priority": "Priority",
  "delivery.type": "Delivery Type",
  "delivery.customer": "Customer",
  "delivery.address": "Address",
  "delivery.phone": "Phone",
  "delivery.courier": "Courier",
  "delivery.restaurant": "Restaurant",
  "delivery.branch": "Branch",
  "delivery.amount": "Amount",
  "delivery.payment": "Payment",
  "delivery.notes": "Notes",
  "delivery.createdAt": "Created At",
  "delivery.updatedAt": "Updated At",
  "delivery.estimatedTime": "Estimated Time",
  "delivery.actualTime": "Actual Time",
  "delivery.items": "Items",
  "delivery.details": "Delivery Details",
  "delivery.new": "New Delivery",
  "delivery.edit": "Edit Delivery",
  "editDialog.general": "General",
  "editDialog.customer": "Customer",
  "editDialog.items": "Items",
  "editDialog.logistics": "Logistics",
  "editDialog.payment": "Payment",
  "editDialog.tracking": "Tracking",
  "editDialog.communication": "Communication",
  "editDialog.metadata": "Metadata",
  "settings.appearance": "Appearance",
  "settings.language": "Language",
  "settings.theme": "Color Theme",
  "settings.darkMode": "Dark Mode",
  "settings.autoTheme": "Auto Mode",
  "settings.seasonalTheme": "Seasonal Theme",
  "settings.notifications": "Notifications",
  "settings.account": "Account",
  "settings.profile": "Profile",
  "settings.security": "Security",
  "settings.privacy": "Privacy",
  "settings.about": "About",
  "settings.system": "System Settings",
  "settings.business": "Business Management",
  "settings.help": "Help",
  "language.he": "עברית",
  "language.en": "English",
  "theme.green": "Green",
  "theme.blue": "Blue",
  "theme.purple": "Purple",
  "theme.orange": "Orange",
  "theme.pink": "Pink",
  "theme.red": "Red",
  "seasonal.none": "Regular",
  "seasonal.hanukkah": "Hanukkah",
  "seasonal.purim": "Purim",
  "seasonal.passover": "Passover",
  "seasonal.independence": "Independence Day",
  "seasonal.summer": "Summer",
  "seasonal.winter": "Winter",
  "dashboard.welcome": "Welcome",
  "dashboard.overview": "Overview",
  "dashboard.statistics": "Statistics",
  "dashboard.recentActivity": "Recent Activity",
  "dashboard.quickActions": "Quick Actions",
  "dashboard.activeDeliveries": "Active Deliveries",
  "dashboard.availableCouriers": "Available Couriers",
  "dashboard.activeRestaurants": "Active Restaurants",
  "dashboard.todayRevenue": "Today's Revenue",
  "dashboard.avgDeliveryTime": "Avg Delivery Time",
  "dashboard.completedToday": "Completed Today",
  "dashboard.cancelledToday": "Cancelled Today",
  "dashboard.pendingOrders": "Pending Orders",
  "dashboard.assignedOrders": "Assigned Orders",
  "dashboard.pickedUpOrders": "Picked Up Orders",
  "dashboard.onTheWayOrders": "On The Way Orders",
  "dashboard.deliveredOrders": "Delivered Orders",
  "topbar.notifications": "Notifications",
  "topbar.userMenu": "User Menu",
  "topbar.profile": "Profile",
  "topbar.settings": "Settings",
  "topbar.logout": "Logout",
  "topbar.balance": "Balance",
  "sidebar.selectBusiness": "Select Business",
  "sidebar.collapse": "Collapse",
  "sidebar.expand": "Expand",
  "sidebar.systemControl": "System Control",
  "sidebar.acceptDeliveries": "Accept Deliveries",
  "sidebar.autoAssign": "Auto Assign",
  "sidebar.deliveryBalance": "Delivery Balance",
  "sidebar.businessManagement": "Business Management",
  "sidebar.systemSettings": "Settings",
  "sidebar.help": "Help",
  "sidebar.statistics": "Statistics",
  "sidebar.reports": "Reports",
  "sidebar.finances": "Finances",
  "sidebar.settings": "Settings",
  "sidebar.noActiveCouriers": "❌ Cannot activate delivery acceptance without connected couriers!",
  "breadcrumbs.home": "Home",
  "breadcrumbs.shipments": "Shipments",
  "breadcrumbs.operatingHours": "Operating Hours",
  "breadcrumbs.deliveryZones": "Delivery Zones",
  "breadcrumbs.distancePricing": "Distance Pricing",
  "breadcrumbs.performance": "Performance",
  "breadcrumbs.shipmentBalance": "Shipment Balance",
  "search.deliveries": "Search deliveries...",
  "search.orderNumber": "Search by order number...",
  "search.customer": "Search by customer...",
  "search.restaurant": "Search by restaurant...",
  "search.general": "Search deliveries... (Ctrl+K)",
  "search.courierDetails": "Search by order number, customer or restaurant...",
  "export.title": "Export Data",
  "export.format": "Format",
  "export.fields": "Fields",
  "export.selectFields": "Select Fields",
  "export.allFields": "All Fields",
  "export.download": "Download",
  "export.csv": "CSV",
  "export.excel": "Excel",
  "export.pdf": "PDF",
  "time.minutes": "minutes",
  "time.hours": "hours",
  "time.days": "days",
  "time.ago": "ago",
  "time.justNow": "just now",
  "action.view": "View",
  "action.edit": "Edit",
  "action.delete": "Delete",
  "action.duplicate": "Duplicate",
  "action.assign": "Assign",
  "action.cancel": "Cancel",
  "action.complete": "Complete",
  "action.print": "Print",
  "action.share": "Share",
  "notification.success": "Operation completed successfully",
  "notification.error": "An error occurred",
  "notification.saved": "Changes saved",
  "notification.deleted": "Item deleted",
  "notification.assigned": "Delivery assigned",
  "notification.cancelled": "Delivery cancelled",
  "empty.noDeliveries": "No deliveries to show",
  "empty.noResults": "No results found",
  "empty.noData": "No data available",
  "empty.addFirst": "Add the first one",
  "validation.required": "Required field",
  "validation.invalidEmail": "Invalid email address",
  "validation.invalidPhone": "Invalid phone number",
  "error.loadFailed": "Failed to load data",
  "error.saveFailed": "Failed to save data",
  "error.connectionFailed": "Connection to server failed"
};
