import { TABLE_WIDTHS } from '../common/table-widths';
import {
  TABLE_ACTIONS_BODY_BASE_CLASS,
  TABLE_ACTIONS_HEAD_CLASS,
  TABLE_CHECKBOX_BODY_CLASS,
  TABLE_CHECKBOX_HEAD_CLASS,
  TABLE_CHECKBOX_LABEL_CLASS,
  TABLE_DATA_CELL_BASE_CLASS,
  TABLE_HEAD_SURFACE_CLASS,
  TABLE_HEADER_CELL_BASE_CLASS,
  TABLE_ROW_HOVER_CLASS,
} from '../common/table-ui';

export const ENTITY_TABLE_WIDTHS = {
  checkbox: TABLE_WIDTHS.checkbox,
  actions: TABLE_WIDTHS.actions,
  xs: TABLE_WIDTHS.status,
  sm: TABLE_WIDTHS.compact,
  md: TABLE_WIDTHS.reference,
  lg: TABLE_WIDTHS.date,
  xl: TABLE_WIDTHS.name,
  name: TABLE_WIDTHS.entityName,
  long: TABLE_WIDTHS.long,
  address: TABLE_WIDTHS.address,
  phone: TABLE_WIDTHS.phone,
  email: TABLE_WIDTHS.email,
} as const;

export const ENTITY_TABLE_HEAD_CLASS = TABLE_HEAD_SURFACE_CLASS;

export const ENTITY_TABLE_CHECKBOX_HEAD_CLASS = TABLE_CHECKBOX_HEAD_CLASS;
export const ENTITY_TABLE_CHECKBOX_BODY_CLASS = TABLE_CHECKBOX_BODY_CLASS;
export const ENTITY_TABLE_CHECKBOX_HEAD_LABEL_CLASS = TABLE_CHECKBOX_LABEL_CLASS;
export const ENTITY_TABLE_CHECKBOX_BODY_LABEL_CLASS = TABLE_CHECKBOX_LABEL_CLASS;

export const ENTITY_TABLE_HEADER_CELL_BASE_CLASS = TABLE_HEADER_CELL_BASE_CLASS;
export const ENTITY_TABLE_DATA_CELL_CLASS = TABLE_DATA_CELL_BASE_CLASS;
export const ENTITY_TABLE_ACTIONS_HEAD_CLASS = TABLE_ACTIONS_HEAD_CLASS;
export const ENTITY_TABLE_ACTIONS_BODY_CLASS = TABLE_ACTIONS_BODY_BASE_CLASS.replace('relative ', '').replace(' transition-colors', '');

export const ENTITY_TABLE_ROW_CLASS = TABLE_ROW_HOVER_CLASS;
